//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocStorage.Repository.Connection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocStorage.Repository.Connection.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE &quot;usergroup&quot;;
        ///DROP TABLE &quot;documentaccess&quot;;
        ///DROP TABLE &quot;group&quot;;
        ///DROP TABLE &quot;document&quot;;
        ///DROP TABLE &quot;user&quot;;
        ///
        ///
        ///CREATE TABLE document (
        ///    &quot;document_id&quot; bigserial NOT NULL,
        ///    &quot;name&quot; text NOT NULL,
        ///    &quot;description&quot; text NOT NULL,
        ///    &quot;category&quot; text NOT NULL,
        ///    &quot;posted_date&quot; timestamp with time zone NOT NULL,
        ///    &quot;extension&quot; text NOT NULL,
        ///    CONSTRAINT &quot;PK_document&quot; PRIMARY KEY (&quot;document_id&quot;)
        ///);
        ///
        ///
        ///CREATE TABLE &quot;group&quot; (
        ///    &quot;group_id&quot; bigserial NOT NULL,
        ///    &quot;name&quot; text NOT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createstructure {
            get {
                return ResourceManager.GetString("createstructure", resourceCulture);
            }
        }
    }
}
