DROP TABLE "usergroup"
DROP TABLE "documentaccess"
DROP TABLE "group"
DROP TABLE "document"
DROP TABLE "user"


CREATE TABLE document (
    "DocumentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "PostedDate" timestamp with time zone NOT NULL,
    "Extension" text NOT NULL,
    CONSTRAINT "PK_document" PRIMARY KEY ("DocumentId")
);


CREATE TABLE "group" (
    "GroupId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_group" PRIMARY KEY ("GroupId")
);


CREATE TABLE "user" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    CONSTRAINT "PK_user" PRIMARY KEY ("UserId")
);


CREATE TABLE documentaccess (
    "DocumentAccessId" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" integer NOT NULL,
    "GroupId" integer NULL,
    "UserId" integer NULL,
    CONSTRAINT "PK_documentaccess" PRIMARY KEY ("DocumentAccessId"),
    CONSTRAINT "FK_documentaccess_document_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES document ("DocumentId") ON DELETE CASCADE,
    CONSTRAINT "FK_documentaccess_group_GroupId" FOREIGN KEY ("GroupId") REFERENCES "group" ("GroupId"),
    CONSTRAINT "FK_documentaccess_user_UserId" FOREIGN KEY ("UserId") REFERENCES "user" ("UserId")
);


CREATE TABLE usergroup (
    "UserGroupId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "GroupId" integer NOT NULL,
    CONSTRAINT "PK_usergroup" PRIMARY KEY ("UserGroupId"),
    CONSTRAINT "FK_usergroup_group_GroupId" FOREIGN KEY ("GroupId") REFERENCES "group" ("GroupId") ON DELETE CASCADE,
    CONSTRAINT "FK_usergroup_user_UserId" FOREIGN KEY ("UserId") REFERENCES "user" ("UserId") ON DELETE CASCADE
);


CREATE INDEX "IX_documentaccess_DocumentId" ON documentaccess ("DocumentId");


CREATE INDEX "IX_documentaccess_GroupId" ON documentaccess ("GroupId");


CREATE INDEX "IX_documentaccess_UserId" ON documentaccess ("UserId");


CREATE INDEX "IX_usergroup_GroupId" ON usergroup ("GroupId");


CREATE INDEX "IX_usergroup_UserId" ON usergroup ("UserId");


